# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 838e99045d603fa184cb8f8764b50f11b3eb81301279af3ab9fc28d12cb6edc95ac72a3f080c1b7f8c008b92dd4e4edc2d3c225e77439886e3331c917a1084db

test:
  secret_key_base: a5512825fd7c86e17013fb21ba1a879cb89515ccc2c50f684729a1e86017e4e92295ca3f6d2fff5298a9411eeb87ee5fea0fa216557ace955ce56ba046e997b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
